// Generated by CoffeeScript 1.6.1
(function() {
  var NEW_COMMENT_SETTING, addNewCommentButton, getNewCommentOptions, loadNewCommentButtons, loadOptions, message, saveOptions;

  NEW_COMMENT_SETTING = "assistocat.newCommentButtons";

  loadOptions = function() {
    this.newCommentOptions = $('#new-comment-options')[0];
    return chrome.storage.sync.get(NEW_COMMENT_SETTING, function(data) {
      var buttons;
      buttons = data[NEW_COMMENT_SETTING];
      return loadNewCommentButtons(buttons);
    });
  };

  loadNewCommentButtons = function(buttons) {
    var button, id, _results;
    if (buttons == null) {
      buttons = {};
    }
    _results = [];
    for (id in buttons) {
      button = buttons[id];
      _results.push(addNewCommentButton(button['title'], button['text'], button['closable']));
    }
    return _results;
  };

  addNewCommentButton = function(title, text, closable) {
    var checkedAttr, commentButton, field;
    if (title == null) {
      title = "";
    }
    if (text == null) {
      text = "";
    }
    if (closable == null) {
      closable = false;
    }
    commentButton = $.parseHTML('<div class="new-comment-button"></div>');
    field = $.parseHTML('<div class="field"></div>');
    $(field).append($.parseHTML("<label>Title:</label>\n<input class=\"title\" value=\"" + title + "\">"));
    $(commentButton).append(field);
    field = $.parseHTML('<div class="field"></div>');
    $(field).append($.parseHTML("<label>Text:</label>\n<textarea class=\"text\">" + text + "</textarea>"));
    $(commentButton).append(field);
    field = $.parseHTML('<div class="field"></div>');
    checkedAttr = closable ? "checked" : "";
    $(field).append($.parseHTML("<label>Close Issue/Pull Request?\n  <input class=\"closable\" type=\"checkbox\" " + checkedAttr + ">\n</label>"));
    $(commentButton).append(field);
    field = $.parseHTML('<div class="field"></div>');
    $(field).append($.parseHTML("<a href='#' class='delete-button'>remove</a>"));
    $(commentButton).append(field);
    field = $.parseHTML('<div class="line-separator"></div>');
    $(commentButton).append(field);
    return $(this.newCommentOptions).append(commentButton);
  };

  getNewCommentOptions = function() {
    var b, buttons, closable, i, node, nodes, text, title, _i, _len;
    buttons = {};
    nodes = $('.new-comment-button');
    for (i = _i = 0, _len = nodes.length; _i < _len; i = ++_i) {
      node = nodes[i];
      title = $(node).find(".title").val();
      text = $(node).find(".text").val();
      closable = $(node).find(".closable").prop('checked');
      b = {
        title: title,
        text: text,
        closable: closable
      };
      buttons["ac-new-comment-button-" + i] = b;
    }
    return buttons;
  };

  saveOptions = function() {
    var options;
    options = {};
    options[NEW_COMMENT_SETTING] = getNewCommentOptions();
    return chrome.storage.sync.set(options, message);
  };

  message = function() {
    return $('.ac-message').slideDown(function() {
      return setTimeout((function() {
        return $('.ac-message').slideUp();
      }), 3000);
    });
  };

  $(function() {
    loadOptions();
    $("#add-new-comment-button").click(function() {
      return addNewCommentButton();
    });
    $("#save-options").click(function() {
      return saveOptions();
    });
    return $(document).on('click', '.delete-button', function() {
      $(this).parent().parent().remove();
      return false;
    });
  });

}).call(this);
